### ISSUE TITLE
Adjust default openjdk versjon to 17.0

### ISSUE THREAD

**Issue by skjolber** [CircleCI-Public/gradle-orb#23]
The current default is 13, which is outdated.

It makes most sense to move to the latest LTS version.

**Comment by ryanbourdais** [comment]
Hi @skjolber that sounds more like an image issue, what image are you using the gradle orb with?

**Comment by ryanbourdais** [comment]
Hi @skjolber, I've spent some time today toying with this and I believe that we are going to keep the default executor at openjdk:13. This is because jdk 13.0 is compatible from gradle 6.0, released in 2019, to 7.6.1 which was released 4 days ago, whereas openjdk 17.0 is open compatible with gradle 7.3 and up, which was released in late 2021. Users can use the [openjdk executor without the orb](https://circleci.com/developer/images/image/cimg/openjdk) if they require jdk 17.0, or they can use the [change open jdk version command](https://circleci.com/developer/orbs/orb/circleci/android#commands-change-java-version) from the android orb if they need to change it during a pipeline.

**Comment by skjolber** [comment]
Why would you ship an [outdated](https://en.wikipedia.org/wiki/Java_version_history) default value in the latest version of an orb? 

Would it not be better that the default value reflects a good choice for the users of this orb? 

If you want backwards compatibility, 11 is the right choice. But this orb has barely changed the last years, the users looking to stay at 13 should could happily use one of the previous versions of this orb?

**Comment by ryanbourdais** [comment]
@skjolber thats a good catch, I didn't think about the fact that 13.0 is not an LTS version of openjdk, I'll open a PR to have it changed to 11 so that our customers will be on an LTS and gradle versions since gradle 5.0, released in 2018, will be able to use the orb default.
